/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import model.Car;
import model.CarFleet;

/**
 *
 * @author TT
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    CarFleet carFleet;
    public CreateJPanel(CarFleet carFleet) {
        initComponents();
        this.carFleet = carFleet;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCreate = new javax.swing.JLabel();
        lblAvailTime = new javax.swing.JLabel();
        txtAvailTime = new javax.swing.JTextField();
        lblAvailFlag = new javax.swing.JLabel();
        lblMadeCompany = new javax.swing.JLabel();
        txtMadeCompany = new javax.swing.JTextField();
        lblYear = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();
        lblSeat = new javax.swing.JLabel();
        txtSeat = new javax.swing.JTextField();
        lblSerialNumber = new javax.swing.JLabel();
        txtSerialNumber = new javax.swing.JTextField();
        lblModelNumber = new javax.swing.JLabel();
        txtModelNumber = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        lblMaintenanceState = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbAvailable = new javax.swing.JCheckBox();
        cbMaintenance = new javax.swing.JCheckBox();

        lblCreate.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        lblCreate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreate.setText("Create  a new Car member");

        lblAvailTime.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblAvailTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAvailTime.setText("Available Time:");

        lblAvailFlag.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblAvailFlag.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAvailFlag.setText("Available:");

        lblMadeCompany.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblMadeCompany.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMadeCompany.setText("Made Company:");

        lblYear.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblYear.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblYear.setText("Year:");

        lblSeat.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblSeat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSeat.setText("Seat:");

        lblSerialNumber.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblSerialNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSerialNumber.setText("Serial Number:");

        lblModelNumber.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblModelNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblModelNumber.setText("Model Number:");

        lblCity.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblCity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCity.setText("City:");

        lblMaintenanceState.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblMaintenanceState.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMaintenanceState.setText("Maintenance Certificate:");

        btnSave.setBackground(new java.awt.Color(127, 255, 170));
        btnSave.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jLabel1.setText("hhmm");

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jLabel2.setText("6 digits");

        cbAvailable.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        cbAvailable.setText("check if available");

        cbMaintenance.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        cbMaintenance.setText("check if MC is valid");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(btnSave))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblModelNumber)
                                .addGap(55, 55, 55)
                                .addComponent(txtModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(lblSeat)
                                            .addGap(55, 55, 55)
                                            .addComponent(txtSeat, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblYear)
                                                .addGap(55, 55, 55)
                                                .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblMadeCompany)
                                                .addGap(55, 55, 55)
                                                .addComponent(txtMadeCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblAvailTime)
                                                    .addComponent(lblAvailFlag))
                                                .addGap(55, 55, 55)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cbAvailable)
                                                    .addComponent(txtAvailTime, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblSerialNumber)
                                        .addGap(55, 55, 55)
                                        .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCity)
                                    .addComponent(lblMaintenanceState))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbMaintenance)
                                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(lblCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblAvailFlag, lblAvailTime, lblCity, lblMadeCompany, lblMaintenanceState, lblModelNumber, lblSeat, lblSerialNumber, lblYear});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(lblCreate)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAvailTime)
                    .addComponent(txtAvailTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAvailFlag)
                    .addComponent(cbAvailable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMadeCompany)
                    .addComponent(txtMadeCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblYear)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSeat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSerialNumber)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblModelNumber)
                    .addComponent(txtModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCity)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaintenanceState)
                    .addComponent(cbMaintenance))
                .addGap(29, 29, 29)
                .addComponent(btnSave)
                .addContainerGap(151, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        int time = 0;
        int timeFlag = 0;
        if(Pattern.compile("^\\d{4}$").matcher(txtAvailTime.getText()).matches() || Pattern.compile("^\\d{3}$").matcher(txtAvailTime.getText()).matches()){
            time = Integer.parseInt(txtAvailTime.getText());
            timeFlag = 1;
        }else timeFlag = 0;

        int avail;
        if(cbAvailable.isSelected()){
            avail = 1;
        }else avail = 0;
        
        String madeCompany = txtMadeCompany.getText();
        
        int year;
        if(Pattern.compile("^\\d{4}$").matcher(txtYear.getText()).matches()){
            year = Integer.parseInt(txtYear.getText());
        }else year = 0;
        
        int seat;
        if(Pattern.compile("^\\d{1,}$").matcher(txtSeat.getText()).matches()){
            seat = Integer.parseInt(txtSeat.getText());
        }else seat = 0;
        
        String serialNumber = null;
        int serialFlag = 1;
        if(Pattern.compile("^\\d{6}$").matcher(txtSerialNumber.getText()).matches()){
            for(Car testCar:carFleet.getCarList()){
                if(testCar.getSerialNumber().equals(txtSerialNumber.getText())) serialFlag = 0; // Serial Number must be unique
            }
            if(serialFlag==1) serialNumber = txtSerialNumber.getText();
        }else serialFlag = 0;
        
        String modelNumber = txtModelNumber.getText();
        String city = txtCity.getText();
        int maintenanceState;
        if(cbMaintenance.isSelected()){
            maintenanceState = 1;
        }else maintenanceState = 0;
        
        if(serialFlag==1 && timeFlag==1){
            Car car = carFleet.addNewCar();
            car.setAvailTime(time);
            car.setAvailFlag(avail);
            car.setMadeCompany(madeCompany);
            car.setYear(year);
            car.setSeat(seat);
            car.setSerialNumber(serialNumber);
            car.setModelNumber(modelNumber);
            car.setCity(city);
            car.setMaintenanceState(maintenanceState);
            
            JOptionPane.showMessageDialog(this, "new Car added.");
             
            // clear
            txtAvailTime.setText("");
            txtCity.setText("");
            txtMadeCompany.setText("");
            txtModelNumber.setText("");
            txtSeat.setText("");
            txtSerialNumber.setText("");
            txtYear.setText("");
            
        }else JOptionPane.showMessageDialog(this, "ERROR: you need to input valid Serial Number and AvailTime!");
        
        
       
        
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox cbAvailable;
    private javax.swing.JCheckBox cbMaintenance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAvailFlag;
    private javax.swing.JLabel lblAvailTime;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCreate;
    private javax.swing.JLabel lblMadeCompany;
    private javax.swing.JLabel lblMaintenanceState;
    private javax.swing.JLabel lblModelNumber;
    private javax.swing.JLabel lblSeat;
    private javax.swing.JLabel lblSerialNumber;
    private javax.swing.JLabel lblYear;
    private javax.swing.JTextField txtAvailTime;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtMadeCompany;
    private javax.swing.JTextField txtModelNumber;
    private javax.swing.JTextField txtSeat;
    private javax.swing.JTextField txtSerialNumber;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
