/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Car;
import model.CarFleet;

/**
 *
 * @author TT
 */
public class SelectJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SelectJPanel
     */
    CarFleet carFleet;
    public SelectJPanel(CarFleet carFleet) {
        initComponents();
        this.carFleet = carFleet;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFindFirstAvailCar = new javax.swing.JButton();
        txtFindFirstAvailCar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCarYear = new javax.swing.JTextField();
        txtCarSerialNum = new javax.swing.JTextField();
        txtMaxSeatNumber = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnAvailCarNumber = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtAvailNumber = new javax.swing.JTextField();
        btnSelectByManufacture = new javax.swing.JButton();
        txtManufactureName = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnCarSelectByYear = new javax.swing.JButton();
        btnCarSelectBySeatNumber = new javax.swing.JButton();
        txtCarModelNum = new javax.swing.JTextField();
        btnCarSelectByModelNUmber = new javax.swing.JButton();
        btnShowManufactures = new javax.swing.JButton();
        btnShowSpecificCar = new javax.swing.JButton();
        btnShowLastUpdateTime = new javax.swing.JButton();
        txtCarCity = new javax.swing.JTextField();
        btnShowCarSelectByCity = new javax.swing.JButton();
        btnShowCarExpiredMC = new javax.swing.JButton();
        txtShowLastTimeUpdate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblShowResult = new javax.swing.JTable();
        txtShowManufacture = new javax.swing.JTextField();
        txtMinSeatNumber = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        btnFindFirstAvailCar.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        btnFindFirstAvailCar.setText("Search");
        btnFindFirstAvailCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindFirstAvailCarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jLabel1.setText("1.Find the first available car");

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jLabel2.setText("Serial Number:");

        jLabel3.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jLabel3.setText("2.Available Car Numbers");

        jLabel4.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jLabel4.setText("3.Show cars selected by Manufacture");

        jLabel5.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jLabel5.setText("4.Show cars selected by year");

        jLabel6.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jLabel6.setText("10.Show cars selected by City");

        txtCarYear.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N

        txtCarSerialNum.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N

        txtMaxSeatNumber.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jLabel7.setText("6.Find the specific car by Serial Number");

        jLabel8.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jLabel8.setText("7.Show cars selected by Model Number");

        jLabel9.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jLabel9.setText("8.Show Manufactures");

        jLabel10.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jLabel10.setText("9.The last time updating car fleet");

        jLabel11.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jLabel11.setText("11.Show cars expired maintenance certificate");

        jLabel12.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jLabel12.setText("5.Show cars selected by seat number");

        btnAvailCarNumber.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        btnAvailCarNumber.setText("Search");
        btnAvailCarNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvailCarNumberActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jLabel13.setText("Available Number:");

        btnSelectByManufacture.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        btnSelectByManufacture.setText("Search");
        btnSelectByManufacture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectByManufactureActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jLabel14.setText("Min:");

        jLabel15.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jLabel15.setText("Max:");

        btnCarSelectByYear.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        btnCarSelectByYear.setText("Search");
        btnCarSelectByYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarSelectByYearActionPerformed(evt);
            }
        });

        btnCarSelectBySeatNumber.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        btnCarSelectBySeatNumber.setText("Search");
        btnCarSelectBySeatNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarSelectBySeatNumberActionPerformed(evt);
            }
        });

        txtCarModelNum.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N

        btnCarSelectByModelNUmber.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        btnCarSelectByModelNUmber.setText("Search");
        btnCarSelectByModelNUmber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarSelectByModelNUmberActionPerformed(evt);
            }
        });

        btnShowManufactures.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        btnShowManufactures.setText(" Show Manufactures:");
        btnShowManufactures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowManufacturesActionPerformed(evt);
            }
        });

        btnShowSpecificCar.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        btnShowSpecificCar.setText("Search");
        btnShowSpecificCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowSpecificCarActionPerformed(evt);
            }
        });

        btnShowLastUpdateTime.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        btnShowLastUpdateTime.setText("Show Update Time:");
        btnShowLastUpdateTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowLastUpdateTimeActionPerformed(evt);
            }
        });

        txtCarCity.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N

        btnShowCarSelectByCity.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        btnShowCarSelectByCity.setText("Search");
        btnShowCarSelectByCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowCarSelectByCityActionPerformed(evt);
            }
        });

        btnShowCarExpiredMC.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        btnShowCarExpiredMC.setText("Show Expired MC cars");
        btnShowCarExpiredMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowCarExpiredMCActionPerformed(evt);
            }
        });

        txtShowLastTimeUpdate.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N

        tblShowResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Car Serial Number", "AvailTime", "AvailorNot", "Manufacture", "Year", "Seat", "ModelNumber", "City", "Maintenance"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblShowResult);

        txtMinSeatNumber.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N

        jLabel16.setText("Manufacture name:");

        jLabel17.setText("Year:");

        jLabel18.setText("Serial Number:");

        jLabel19.setText("Model Number:");

        jLabel20.setText("City:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(btnAvailCarNumber))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(btnFindFirstAvailCar)))
                            .addGap(73, 73, 73)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtAvailNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtFindFirstAvailCar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel17)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(38, 38, 38)
                                    .addComponent(jLabel16))
                                .addComponent(jLabel15))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtManufactureName, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnSelectByManufacture))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtCarYear, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnCarSelectByYear))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtMinSeatNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(53, 53, 53)
                            .addComponent(txtMaxSeatNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnCarSelectBySeatNumber))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnShowLastUpdateTime, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnShowManufactures, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel20)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtCarCity, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnShowCarSelectByCity))
                                .addComponent(txtShowManufacture, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtCarModelNum, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnCarSelectByModelNUmber))
                                .addComponent(txtShowLastTimeUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(201, 201, 201))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addGap(18, 18, 18)
                            .addComponent(btnShowCarExpiredMC)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCarSerialNum, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnShowSpecificCar)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFindFirstAvailCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFindFirstAvailCar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnAvailCarNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtAvailNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtManufactureName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelectByManufacture, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCarYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCarSelectByYear, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtMaxSeatNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(btnCarSelectBySeatNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMinSeatNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCarSerialNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnShowSpecificCar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCarModelNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCarSelectByModelNUmber, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(btnShowManufactures, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtShowManufacture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(btnShowLastUpdateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtShowLastTimeUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCarCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnShowCarSelectByCity, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(btnShowCarExpiredMC, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(231, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel10, jLabel11, jLabel12, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9});

    }// </editor-fold>//GEN-END:initComponents

    private void btnFindFirstAvailCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindFirstAvailCarActionPerformed
        // TODO add your handling code here:
        
        Car targetCar = new Car();
        int tempTime = 2401;
        for(Car temp : carFleet.getCarList()){
            if(temp.getAvailTime()<tempTime){
                targetCar = temp;
                tempTime = temp.getAvailTime();
            }
        }
        JOptionPane.showMessageDialog(this, "Successfully find the first Car available.");
        String temp1 = targetCar.getSerialNumber();
        int temp2 = targetCar.getAvailTime();
        int j = temp2 / 100;
        int k = temp2 % 100;
        String result;
        if(k == 0){
            result = "No." + temp1 + " : avail at " + j + ":" + k + "0";
        }else{
            result = "No." + temp1 + " : avail at " + j + ":" + k;
        }
        txtFindFirstAvailCar.setText(result);
        
    }//GEN-LAST:event_btnFindFirstAvailCarActionPerformed

    private void btnAvailCarNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvailCarNumberActionPerformed
        // TODO add your handling code here:
        
        int availCount = 0;
        int overallCar = carFleet.getCarList().size();
        for(Car temp : carFleet.getCarList()){
            if(temp.getAvailFlag() == 1){
                availCount++;
            }
        }
        JOptionPane.showMessageDialog(this, "Successfully find the available car number.");
        String result = "available car number: " + availCount + " out of " + overallCar;
        txtAvailNumber.setText(result);
        
    }//GEN-LAST:event_btnAvailCarNumberActionPerformed

    private void btnSelectByManufactureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectByManufactureActionPerformed
        // TODO add your handling code here:
        
        CarFleet newFleet = new CarFleet();
        String manuName = txtManufactureName.getText();
        if(manuName.equals("")) {
            JOptionPane.showMessageDialog(this, "ERROR: input valid Manufacture Name!");
        }else{
            for(Car temp : carFleet.getCarList()){
                if(temp.getMadeCompany().equals(manuName)){
                    newFleet.addNewCar(temp);
                }
            }
            JOptionPane.showMessageDialog(this, "Successfully find the car selected by manufacture: "+ newFleet.getCarList().size() + ".");
            displayTable(newFleet);
        }
    }//GEN-LAST:event_btnSelectByManufactureActionPerformed

    private void btnCarSelectByYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarSelectByYearActionPerformed
        // TODO add your handling code here:
        
        CarFleet newFleet = new CarFleet();
        if(txtCarYear.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "ERROR: input valid Year!");
        }else{
            int carYear = Integer.parseInt(txtCarYear.getText());
            for(Car temp : carFleet.getCarList()){
                if(temp.getYear()==(carYear)){
                    newFleet.addNewCar(temp);
                }
            }
            JOptionPane.showMessageDialog(this, "Successfully find the car selected by year: "+ newFleet.getCarList().size() + ".");
            displayTable(newFleet);
        }
    }//GEN-LAST:event_btnCarSelectByYearActionPerformed

    private void btnCarSelectBySeatNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarSelectBySeatNumberActionPerformed
        // TODO add your handling code here:
        
        CarFleet newFleet = new CarFleet();
        if(txtMinSeatNumber.getText().equals("")||txtMaxSeatNumber.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "ERROR: input valid Seat!");
        }else{
            int carSeatMin = Integer.parseInt(txtMinSeatNumber.getText());
            int carSeatMax = Integer.parseInt(txtMaxSeatNumber.getText());
            for(Car temp : carFleet.getCarList()){
                if(temp.getSeat()>=carSeatMin && temp.getSeat()<=carSeatMax && temp.getSeat()!=0){
                    newFleet.addNewCar(temp);
                }
            }
            JOptionPane.showMessageDialog(this, "Successfully find the car selected by seat: "+ newFleet.getCarList().size() + ".");
            displayTable(newFleet);
        }
    }//GEN-LAST:event_btnCarSelectBySeatNumberActionPerformed

    private void btnCarSelectByModelNUmberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarSelectByModelNUmberActionPerformed
        // TODO add your handling code here:
        
        CarFleet newFleet = new CarFleet();
        if(txtCarModelNum.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "ERROR: input valid Model Number!");
        }else{
            String carModelNum = txtCarModelNum.getText();
            for(Car temp : carFleet.getCarList()){
                if(temp.getModelNumber().equals(carModelNum)){
                    newFleet.addNewCar(temp);
                }
            }
            JOptionPane.showMessageDialog(this, "Successfully find the car selected by model number: "+ newFleet.getCarList().size() + ".");
            displayTable(newFleet);
        }
    }//GEN-LAST:event_btnCarSelectByModelNUmberActionPerformed

    private void btnShowManufacturesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowManufacturesActionPerformed
        // TODO add your handling code here:
        
        HashSet<String> carSet = new HashSet<String>();  
        String result = "";
        for(Car temp : carFleet.getCarList()){
            if(!temp.getMadeCompany().equals("")) carSet.add(temp.getMadeCompany());   // will not include repeat elements or "" element
        }
        JOptionPane.showMessageDialog(this, "Successfully find all of the manufactures: "+ carSet.size() + ".");
        for(String str:carSet){
            result = result + str + " | ";
        }
        txtShowManufacture.setText(result);
    }//GEN-LAST:event_btnShowManufacturesActionPerformed

    private void btnShowSpecificCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowSpecificCarActionPerformed
        // TODO add your handling code here:
        
        CarFleet newFleet = new CarFleet();
        if(txtCarSerialNum.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "ERROR: input valid Serial Number!");
        }else{
            String carSerialNum = txtCarSerialNum.getText();
            for(Car temp : carFleet.getCarList()){
                if(temp.getSerialNumber().equals(carSerialNum)){
                    newFleet.addNewCar(temp);
                    break; // only one
                }
            }
            JOptionPane.showMessageDialog(this, "Successfully find the car selected by serial number: "+ newFleet.getCarList().size() + ".");
            displayTable(newFleet);
        }
    }//GEN-LAST:event_btnShowSpecificCarActionPerformed

    private void btnShowLastUpdateTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowLastUpdateTimeActionPerformed
        // TODO add your handling code here:
        
        Date date = carFleet.getUpdateTime();
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss"); 
        txtShowLastTimeUpdate.setText(formatter.format(date));
        
    }//GEN-LAST:event_btnShowLastUpdateTimeActionPerformed

    private void btnShowCarSelectByCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowCarSelectByCityActionPerformed
        // TODO add your handling code here:
        
        CarFleet newFleet = new CarFleet();
        if(txtCarCity.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "ERROR: input valid City Name!");
        }else{
            String carCity = txtCarCity.getText();
            for(Car temp : carFleet.getCarList()){
                if(temp.getCity().equals(carCity)){
                    newFleet.addNewCar(temp);
                }
            }
            JOptionPane.showMessageDialog(this, "Successfully find the car selected by city: "+ newFleet.getCarList().size() + ".");
            displayTable(newFleet);
        }
    }//GEN-LAST:event_btnShowCarSelectByCityActionPerformed

    private void btnShowCarExpiredMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowCarExpiredMCActionPerformed
        // TODO add your handling code here:
        
        CarFleet newFleet = new CarFleet();
        for(Car temp : carFleet.getCarList()){
            if(temp.getMaintenanceState()!=1){
                newFleet.addNewCar(temp);
            }
        }
        JOptionPane.showMessageDialog(this, "Successfully find the car expired maintenance certificate: "+ newFleet.getCarList().size() + ".");
        displayTable(newFleet);
        
    }//GEN-LAST:event_btnShowCarExpiredMCActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvailCarNumber;
    private javax.swing.JButton btnCarSelectByModelNUmber;
    private javax.swing.JButton btnCarSelectBySeatNumber;
    private javax.swing.JButton btnCarSelectByYear;
    private javax.swing.JButton btnFindFirstAvailCar;
    private javax.swing.JButton btnSelectByManufacture;
    private javax.swing.JButton btnShowCarExpiredMC;
    private javax.swing.JButton btnShowCarSelectByCity;
    private javax.swing.JButton btnShowLastUpdateTime;
    private javax.swing.JButton btnShowManufactures;
    private javax.swing.JButton btnShowSpecificCar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblShowResult;
    private javax.swing.JTextField txtAvailNumber;
    private javax.swing.JTextField txtCarCity;
    private javax.swing.JTextField txtCarModelNum;
    private javax.swing.JTextField txtCarSerialNum;
    private javax.swing.JTextField txtCarYear;
    private javax.swing.JTextField txtFindFirstAvailCar;
    private javax.swing.JTextField txtManufactureName;
    private javax.swing.JTextField txtMaxSeatNumber;
    private javax.swing.JTextField txtMinSeatNumber;
    private javax.swing.JTextField txtShowLastTimeUpdate;
    private javax.swing.JTextField txtShowManufacture;
    // End of variables declaration//GEN-END:variables

    private void displayTable(CarFleet newFleet) {
        DefaultTableModel model = (DefaultTableModel) tblShowResult.getModel();
        model.setRowCount(0);
        
        for(Car che: newFleet.getCarList()){
            Object[] row = new Object[9];
            row[0] = che.getSerialNumber();  
            int t = che.getAvailTime();
            int j = t / 100;
            int k = t % 100;
            if(k==0){
                row[1] = j + ":" + k + "0";
            }else row[1] = j + ":" + k;
            if(che.getAvailFlag()==1){
                row[2] = "Yes";
            }else row[2] = "No";
            row[3] = che.getMadeCompany();
            if(che.getYear()==0){
                row[4] = null;
            }else row[4] = che.getYear();
            if(che.getSeat()==0){
                row[5] = null;
            }else row[5] = che.getSeat();
            row[6] = che.getModelNumber();
            row[7] = che.getCity();
            if(che.getMaintenanceState()==1){
                row[8] = "Valid";
            }else row[8] = "Expired";
            
            model.addRow(row);
        }
        
    }
}
